### PR TITLE
locksmithctl: use IANA port

### PR DESCRIPTION
**Pull request by philips**
Try to use the etcd IANA port by default.

Also part of coreos/bugs#317

### CODE REVIEW

**Comment by crawford** [comment]
LGTM

**Comment by philips** [comment]
cc @jonboulle

**Comment by jonboulle** [comment]
I have a mild apprehension nagging at the back of my mind about splitbrains if people somehow start etcd and etcd2 side-by-side (each listening on a separate port), but I think we are going to prevent that if at all possible on the systemd side and it would probably cause various other byzantine failures anyway, so this lgtm..

**Comment by marineam** [comment]
@jonboulle correct, the units we are shipping for etcd and etcd2 will conflict each other. Also by default etcd2 listens on both ports so that adds another possible way for the two to block eachother. Of course a user can change configurations to run both but at that point it is out of our hands.

**Pull request merged**
