### PR TITLE
Makefile: automatically set up GOPATH

### PR DESCRIPTION
**Pull request by bgilbert**

### CODE REVIEW

**Comment by sdemos** [comment]
running `make test` fails for me with this. adding `-x` to the test script shows that it is getting really strange names for packages to try and test and then failing when those paths don't exist anywhere. 

```
+ ORG_PATH=github.com/coreos
+ REPO_PATH=github.com/coreos/locksmith
++ cd gopath/src/github.com/coreos/locksmith
++ go list ./...
++ grep -v vendor
+ PKGS='_/home/demos/work/coreos/locksmith/gopath/src/github.com/coreos/locksmith/lock
_/home/demos/work/coreos/locksmith/gopath/src/github.com/coreos/locksmith/locksmithctl
_/home/demos/work/coreos/locksmith/gopath/src/github.com/coreos/locksmith/pkg/coordinatorconf
_/home/demos/work/coreos/locksmith/gopath/src/github.com/coreos/locksmith/pkg/filelock
_/home/demos/work/coreos/locksmith/gopath/src/github.com/coreos/locksmith/pkg/machineid
_/home/demos/work/coreos/locksmith/gopath/src/github.com/coreos/locksmith/pkg/timeutil
_/home/demos/work/coreos/locksmith/gopath/src/github.com/coreos/locksmith/updateengine
_/home/demos/work/coreos/locksmith/gopath/src/github.com/coreos/locksmith/version'
```

for some reason this doesn't happen when I try and run the commands manually, it only seems to happen when the command is run from make.

**Comment by sdemos** [comment]
also it looks like the `go vet` command fails if it's not in the `gopath/src/${REPO_PATH}` directory. it seems to be happy if I cd to that directory before `go vet` and then cd back after. in fact, moving to the gopath repository at the beginning of the script seems to fix the previous problem I pointed out as well.

**Comment by sdemos** [comment]
after more investigation, this seems to be an artifact of my setup. I work in a part of my gopath that is symlinked somewhere else. if I go the real folder in the gopath, I can run `make test` successfully. I might dive into this further at some point, but let's go ahead and merge this for now.

**Comment by bgilbert** [comment]
Good to merge.

**Pull request merged**
