### PR TITLE
daemon: check etcd connection instead of service

### PR DESCRIPTION
**Pull request by crawford**
Rather than checking to see if a local instance of etcd.service is
running, check to see if the configured etcd endpoint can be reached.
This will allow support for those using "best-effort" with a non-local
etcd installation or those using etcd2 in the future.

### CODE REVIEW

**Comment by crawford** [comment]
Fixes https://github.com/coreos/locksmith/issues/69 and https://github.com/coreos/locksmith/issues/72.

**Comment by marineam** [comment]
What about doing both? The reason for the service check was to avoid
assuming was safe to reboot if etcd was supposed to be up but had crashed
or some other unknown mystery was afoot.

**Comment by crawford** [comment]
@marineam If the user truly depends on the etcd lock, they will need to set their reboot-strategy to "etcd-lock". This new approach aligns more with our documentation around the behavior of "best-effort" (if etcd is crashed, then it is not running).

**Comment by marineam** [comment]
I would argue that if the user configures a remote etcd endpoint that the
strategy should then be etcd-lock and best effort is only applicable to the
minimal configuration local etcd cluster situation. Best-effort shouldn't
depend on the network working correctly in order to make a decision. Best
effort needs to be dumb and only consider state that is reliable to query.

**Comment by crawford** [comment]
That's fair. Unfortunately, the state local to the machine is just not adequate. The extra piece of information we need is whether or not etcd should be used (which comes from the user's config). It really sounds like "best-effort" was a mistake. It should have been a black and white decision from the start.

**Comment by philips** [comment]
I am working on this one.

**Comment by philips** [comment]
Patch posted at #74

**Pull request closed without merging**
