### PR TITLE
Add update coordinator config package and use it

### PR DESCRIPTION
**Pull request by euank**
This is part of https://github.com/coreos/container-linux-update-operator/issues/88

This is WIP because it still needs to be tested.

### CODE REVIEW

**Comment by euank** [comment]
Removing WIP, I've done manual testing and I don't know of any problems with it.

cc @sdemos @lucab for review

**Comment by squeed** [comment]
Seems reasonable. Bikeshedding times one million: Does it make sense to move rkt/pkg/lock in to coreos/pkg/lock?

**Comment by euank** [comment]
If someone else cares enough to move it to `coreos/pkg/lock`, we can update the vendor/import here. I don't.

**Comment by euank** [comment]
*sigh* and of course as soon as I merge it I find issues with it.

I'll post a followup since this doesn't quite work. Notably, it should create more permissive directory/file permissions so an unprivileged user can read the status of update engine (since unprivileged shells also want that information).

**Pull request merged**
