### PR TITLE
lock: etcd/client returns values, not pointers for errors

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by jonboulle** [comment]
How come the test didn't catch this? :/

**Comment by mischief** [comment]
the test code was using &client.Errors (pointers). nothing is really checking error type (ptr vs value).

took me a bit to realize what was going on - values, not pointers are created in https://github.com/coreos/etcd/blob/master/client/keys.go#L645

**Comment by jonboulle** [comment]
How'd you notice?

Nick Owens <notifications@github.com> schrieb am Sa., 6. Feb. 2016 16:51:

**Comment by mischief** [comment]
https://github.com/coreos/locksmith/blob/master/lock/etcd.go#L76 failing because `ErrorCodeNodeExist` was not caught correctly.

**Pull request merged**
