### PR TITLE
*: convert to etcd/client

### PR DESCRIPTION
**Pull request by mischief**
this is yet to be tested against etcd 0.4.9 (or etcd2 for that matter), but i'm putting it out there.

### CODE REVIEW

**Comment by jonboulle** [comment]
This is unreviewable :-(. Can you split into two commits?

**Comment by mischief** [comment]
@jonboulle ptal

**Comment by mischief** [comment]
this has been tested against etcd 0.4.9. locksmithctl lock/unlock/status/reboot all work.

**Comment by mischief** [comment]
tested against etcd v2.2.4, locksmithctl lock/unlock/status/reboot all work.

**Comment by mischief** [comment]
ping @jonboulle

**Comment by jonboulle** [comment]
awesome!! thanks for doing this!

**Comment by mischief** [comment]
can't wait for v3... ;)

**Comment by mischief** [comment]
PTAL

**Comment by jonboulle** [comment]
if it all works, LGTM!!

**Pull request merged**
